# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c55e2da7907fdb4673193a6f329145b0d8585332f14d4d93682d39ce41138628decc2a28d0f0027fd925587a78440563dc79975cb75420d879c4ef230f52a73b

test:
  secret_key_base: 1e39550d6fe4755994e137b251585a5dc6589a37a4da517cecef9719e38b6bc5deaae8f896c70229293d7be2c9e883068e5f11ffa155019fa5ad361884ba0f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
